package:
  name: pdbfixer-dev
  version: dev

requirements:
  build:
    - python
    - setuptools
    - openmm
    - numpy

  run:
    - python
    - openmm
    - numpy

test:
  requires:
    - nose

  commands:
    - nosetests pdbfixer --nocapture --verbosity=2 --with-doctest

about:
  home: http://github.com/pandegroup/pdbfixer
  license: free
  summary: PDBFixer fixes problems in PDB files to prepare them for molecular simulation.
